config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contatos', to: 'home#contatos', as: 'busca_contatos'
  post '/contatos', to: 'home#contatos'
  get '/departamentos', to: 'home#departamentos', as: 'busca_departamentos'
  post '/departamentos', to: 'home#departamentos'
  get 'locais', to: 'home#locais', as: 'busca_locais'
  post 'locais', to: 'home#locais'
  get '/usuarios/alterarsenha', to: 'usuarios#alterar_senha', as: 'alterar_senha'
  patch '/usuarios/alterarsenha', to: 'usuarios#atualizar_senha'
  devise_for :usuarios, controllers: { sessions: 'usuario/sessions' }
  namespace :cadastro do
    resources :contatos
    resources :departamentos
    resources :locais
  end
  resources :usuarios, except: :show
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :acesso_cadastro?

  def index
    # @contatos = Contato.busca(@busca_params).page(params[:page])
    @contatoq = Contato.ransack(params[:q])
    @departamentoq = Departamento.ransack(params[:q])
    @localq = Local.ransack(params[:q])
  end

  def contatos
    @q = Contato.ransack(params[:q])
    @contatos = @q.result.ativos.includes(departamento: [:local]).order(:nome).page(params[:page])
    render 'resultados'
  end

  def departamentos
    @q = Departamento.ransack(params[:q])
    @departamentos = @q.result.includes(:local).order(:nome).page(params[:page])
    render 'resultados'
  end

  def locais
    @q = Local.ransack(params[:q])
    @locais = @q.result.order(:nome).page(params[:page])
    render 'resultados'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_resultados_contatos.html.erb
<div class="container">
  <%= search_form_for @q, class: 'form-inline mt-3 mb-3', id: 'form-busca-contato' do |f| %>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.search_field :nome_cont, class: 'form-control ml-3' %>
    </div>

    <div class="form-group ml-3">
      <%= f.label :numero %>
      <%= f.search_field :telefone_or_celular_cont, class: 'form-control ml-3', id: 'campo-numero-telefone-celular' %>
    </div>

    <div class="form-group ml-3 mr-3">
      <%= f.label 'Departamento'%>
      <%= f.search_field :departamento_nome_cont, class: 'form-control ml-3' %>
    </div>

    <div id="submit">
      <%= f.submit 'Buscar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :nome, 'Nome', default_order: :asc) %></th>
        <th><%= sort_link(@q, :telefone, 'Telefone', default_order: :asc) %></th>
        <th><%= sort_link(@q, :celular, 'Celular', default_order: :asc) %></th>
        <th><%= sort_link(@q, :cargo, 'Cargo', default_order: :asc) %></th>
        <th><%= sort_link(@q, :departamento, 'Departamento', default_order: :asc) %></th>
        <th><%= sort_link(@q, :local, 'Local', default_order: :asc) %></th>
      </tr>
    </thead>
    <tbody>
      <% @contatos.each do |contato| %>
        <tr>
          <td><%= contato.nome %></td>
          <td><%= formata_telefone contato.telefone %></td>
          <td><%= formata_celular contato.celular %></td>
          <td><%= contato.cargo %></td>
          <td><%= contato.departamento.nome %></td>
          <td><%= contato.departamento.local.nome %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pagination justify-content-center">
  <%= paginate @contatos, theme: 'twitter-bootstrap-4' %>
</div>

app/views/home/_resultados_departamentos.html.erb
<div class="container">
  <%= search_form_for @q, class: 'form-inline mt-3 mb-3' do |f| %>
    <div class="form-group mr-3">
      <%= f.label :nome %>
      <%= f.search_field :nome_cont, class: 'form-control ml-3' %>
    </div>

    <div class="form-group mr-3">
      <%= f.label :telefone %>
      <%= f.search_field :telefone_cont, class: 'form-control ml-3' %>
    </div>

    <div class="form-group mr-3">
      <%= f.label 'Local'%>
      <%= f.search_field :local_nome_cont, class: 'form-control ml-3' %>
    </div>

    <div id="submit">
      <%= f.submit 'Buscar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :nome, 'Nome', default_order: :asc) %></th>
        <th><%= sort_link(@q, :telefone, 'Telefone', default_order: :asc) %></th>
        <th><%= sort_link(@q, :local, 'Local', default_order: :asc) %></th>
      </tr>
    </thead>
    <tbody>
      <% @departamentos.each do |departamento| %>
        <tr>
          <td><%= departamento.nome %></td>
          <td><%= formata_telefone departamento.nome %></td>
          <td><%= departamento.local.nome %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pagination justify-content-center">
  <%= paginate @departamentos, theme: 'twitter-bootstrap-4' %>
</div>

app/views/home/_resultados_locais.html.erb
<div class="container">
  <%= search_form_for @q, class: 'form-inline mt-3 mb-3', id: 'form-busca-local' do |f| %>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.search_field :nome_cont, class: 'form-control ml-3 mr-3' %>
    </div>

    <div class="form-group">
      <%= f.label :telefone %>
      <%= f.search_field :telefone_cont, class: 'form-control ml-3 mr-3', id: 'campo-numero-telefone' %>
    </div>

    <div id="submit">
      <%= f.submit 'Buscar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :nome, 'Nome', default_order: :asc) %></th>
        <th><%= sort_link(@q, :telefone, 'Telefone', default_order: :asc) %></th>
      </tr>
    </thead>
    <tbody>
      <% @locais.each do |local| %>
        <tr>
          <td><%= local.nome %></td>
          <td><%= formata_telefone local.telefone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pagination justify-content-center">
  <%= paginate @locais, theme: 'twitter-bootstrap-4' %>
</div>

app/views/home/index.html.erb
<div class="container main-container">
  <div class="card-deck">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Contatos</h5>

        <%= search_form_for @contatoq, url: busca_contatos_path, id: 'form-busca-contato' do |f| %>
          <div class="form-group">
            <%= f.label :nome %>
            <%= f.search_field :nome_cont, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :numero %>
            <%= f.search_field :telefone_or_celular_cont, class: 'form-control', id: 'campo-numero-telefone-celular' %>
          </div>

          <div id="submit">
            <%= f.submit 'Buscar', class: 'btn btn-outline-secondary' %>
          </div>
        <% end %>

        <div class="mt-3">
          <%= link_to 'Ver todos', busca_contatos_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Departamentos</h5>

        <%= search_form_for @departamentoq, url: busca_departamentos_path do |f| %>
          <div class="form-group">
            <%= f.label :nome %>
            <%= f.search_field :nome_cont, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :telefone %>
            <%= f.search_field :telefone_cont, class: 'form-control' %>
          </div>

          <div id="submit">
            <%= f.submit 'Buscar', class: 'btn btn-outline-secondary' %>
          </div>
        <% end %>

        <div class="mt-3">
          <%= link_to 'Ver todos', busca_departamentos_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Locais</h5>

        <%= search_form_for @localq, url: locais_path, id: 'form-busca-local' do |f| %>
          <div class="form-group">
            <%= f.label :nome %>
            <%= f.search_field :nome_cont, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :telefone %>
            <%= f.search_field :telefone_cont, class: 'form-control', id: 'campo-numero-telefone' %>
          </div>

          <div id="submit">
            <%= f.submit 'Buscar', class: 'btn btn-outline-secondary' %>
          </div>
        <% end %>

        <div class="mt-3">
          <%= link_to 'Ver todos', locais_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/resultados.html.erb
<% if action_name == 'departamentos' %>
  <%= render 'resultados_departamentos' %>
<% elsif action_name == 'contatos' %>
  <%= render 'resultados_contatos' %>
<% elsif action_name == 'locais' %>
  <%= render 'resultados_locais' %>
<% end %>