config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contatos', to: 'home#contatos', as: 'busca_contatos'
  post '/contatos', to: 'home#contatos'
  get '/departamentos', to: 'home#departamentos', as: 'busca_departamentos'
  post '/departamentos', to: 'home#departamentos'
  get 'locais', to: 'home#locais', as: 'busca_locais'
  post 'locais', to: 'home#locais'
  get '/usuarios/alterarsenha', to: 'usuarios#alterar_senha', as: 'alterar_senha'
  patch '/usuarios/alterarsenha', to: 'usuarios#atualizar_senha'
  devise_for :usuarios, controllers: { sessions: 'usuario/sessions' }
  namespace :cadastro do
    resources :contatos
    resources :departamentos
    resources :locais
  end
  resources :usuarios, except: :show
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :departamento
  validates :nome, presence: true
  validate :numero_informado, :valida_telefone, :valida_celular
  before_save :remover_caracteres

  scope :ativos, -> { where(ativo: true) }

  private

  def numero_informado
    if telefone.blank? && celular.blank?
      errors.add(:telefone, 'não pode ficar em branco.')
      errors.add(:celular, 'não pode ficar em branco.')
    end
  end

  def valida_telefone
    unless telefone.present?
      errors.add(:telefone, 'está em formato inválido') unless telefone.gsub(/[()\s-]/, '') =~ /(^\d{8}\z|^\d{10}\z)/
    end
  end

  def valida_celular
    unless celular.present?
      errors.add(:celular, 'está em formato inválido') unless celular.gsub(/[()\s-]/, '') =~ /(^\d{9}\z|^\d{11}\z)/
    end
  end

  def remover_caracteres
    telefone&.gsub!(/[()\s-]/, '')
    celular&.gsub!(/[()\s-]/, '')
  end
end

app/controllers/cadastro/contatos_controller.rb
class Cadastro::ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :set_departamento, only: [:new, :edit, :create, :update]

  # GET /contatos
  # GET /contatos.json
  def index
    @q = Contato.ransack(params[:q])
    @contatos = @q.result.includes(departamento: [:local]).order(:nome).page(params[:page])
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, flash: { success: 'Contato was successfully created.' } }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, flash: { success: 'Contato was successfully updated.' } }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, flash: { success: 'Contato was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contato
    @contato = Contato.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contato_params
    params.require(:contato).permit(:departamento_id, :nome, :telefone, :celular, :cargo, :ativo)
  end

  def set_departamento
    @departamentos = Departamento.all.select :id, :nome
  end
end

app/controllers/cadastro/departamentos_controller.rb
class Cadastro::DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]
  before_action :set_locais, only: [:new, :edit, :update, :create]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @q = Departamento.ransack(params[:q])
    @departamentos = @q.result.includes(:local).order(:nome).page(params[:page])
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, flash: { success: 'Departamento was successfully created.' } }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, flash: { success: 'Departamento was successfully updated.' } }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, flash: { success: 'Departamento was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_departamento
    @departamento = Departamento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def departamento_params
    params.require(:departamento).permit(:local_id, :nome, :telefone)
  end

  def set_locais
    @locais = Local.all.select(:id, :nome)
  end
end

app/controllers/cadastro/locais_controller.rb
class Cadastro::LocaisController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locais
  # GET /locais.json
  def index
    @q = Local.ransack(params[:q])
    @locais = @q.result.order(:nome).page(params[:page])
  end

  # GET /locais/1
  # GET /locais/1.json
  def show
  end

  # GET /locais/new
  def new
    @local = Local.new
    @local.build_endereco
  end

  # GET /locais/1/edit
  def edit
  end

  # POST /locais
  # POST /locais.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, flash: { success: 'Local was successfully created.' } }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locais/1
  # PATCH/PUT /locais/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, flash: { success: 'Local was successfully updated.' } }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locais/1
  # DELETE /locais/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locais_url, flash: { success: 'Local was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_local
    @local = Local.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def local_params
    params.require(:local).permit(:nome, :telefone, endereco_attributes: [ :cep, :rua, :bairro, :cidade, :estado ])
  end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :set_departamento, only: [:new, :edit, :create, :update]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all.order(:nome).includes(:departamento).page(params[:page])
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, flash: { success: 'Contato was successfully created.' } }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, flash: { success: 'Contato was successfully updated.' } }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, flash: { success: 'Contato was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contato
    @contato = Contato.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contato_params
    params.require(:contato).permit(:departamento_id, :nome, :telefone, :celular, :cargo, :ativo)
  end

  def set_departamento
    @departamentos = Departamento.all.select :id, :nome
  end
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/cadastro/contatos/_form.html.erb
<%= form_with(model: [:cadastro, contato], local: true) do |form| %>
  <div class="form-row align-items-center">
    <div class="form-group col-auto">
      <%= form.label :nome %>
      <%= form.text_field :nome, class: 'form-control' %>
    </div>

    <div class="form-check col-auto">
      <div class="custom-control custom-checkbox">
        <%= form.check_box :ativo, class: 'custom-control-input' %>
        <%= form.label :ativo, class: 'custom-control-label' %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :telefone %>
      <%= form.text_field :telefone, class: 'form-control' %>
    </div>

    <div class="form-group col-auto">
      <%= form.label :celular %>
      <%= form.text_field :celular, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :departamento %>
      <%= form.select :departamento_id, departamentos.collect { |d| [ d.nome, d.id ] }, { prompt: 'Selecione' }, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :cargo %>
      <%= form.text_field :cargo, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
    <%= link_to 'Voltar', cadastro_contatos_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<%= model_erros_to_js_array contato %>

app/views/cadastro/contatos/edit.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h1>Editar Contato</h1>
    </div>
    <div class="card-body">
      <%= render 'form', contato: @contato, departamentos: @departamentos %>
    </div>
  </div>
</div>

app/views/cadastro/contatos/index.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-auto">
      <h1>Cadastro de Contatos</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-auto mr-auto">
      <%= search_form_for @q, class: 'form-inline mb-3', id: 'form-busca-contato' do |f| %>
        <div class="form-group">
          <%= f.label :nome %>
          <%= f.search_field :nome_cont, class: 'form-control ml-3' %>
        </div>

        <div class="form-group ml-3">
          <%= f.label :numero %>
          <%= f.search_field :telefone_or_celular_cont, class: 'form-control ml-3', id: 'campo-numero-telefone-celular' %>
        </div>

        <div class="form-group ml-3 mr-3">
          <%= f.label 'Departamento'%>
          <%= f.search_field :departamento_nome_cont, class: 'form-control ml-3' %>
        </div>

        <div id="submit">
          <%= f.submit 'Buscar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-auto mr-auto mb-3">
      <%= link_to 'Novo Contato', new_cadastro_contato_path, class: 'btn btn-primary mt-1' %>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :nome, 'Nome', default_order: :asc) %></th>
        <th><%= sort_link(@q, :telefone, 'Telefone', default_order: :asc) %></th>
        <th><%= sort_link(@q, :celular, 'Celular', default_order: :asc) %></th>
        <th><%= sort_link(@q, :cargo, 'Cargo', default_order: :asc) %></th>
        <th><%= sort_link(@q, :departamento_nome, 'Departamento', default_order: :asc) %></th>
        <th><%= sort_link(@q, :departamento_local_nome, 'Local', default_order: :asc) %></th>
        <th style="text-align: center"><%= sort_link(@q, :ativo, 'Ativo', default_order: :asc) %></th>
        <th style="text-align: center">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @contatos.each do |contato| %>
        <tr>
          <td><%= contato.nome %></td>
          <td><%= formata_telefone contato.telefone %></td>
          <td><%= formata_celular contato.celular %></td>
          <td><%= contato.cargo %></td>
          <td><%= contato.departamento.nome %></td>
          <td><%= contato.departamento.local.nome %></td>
          <td style="text-align: center"><%= t contato.ativo %></td>
          <td style="text-align: center">
            <%= link_to fa_icon('pencil'), edit_cadastro_contato_path(contato), class: 'btn btn-primary btn-sm' %>
            <%= link_to fa_icon('trash'), [:cadastro, contato], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<div class="pagination justify-content-center">
  <%= paginate @contatos, theme: 'twitter-bootstrap-4' %>
</div>

app/views/cadastro/contatos/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h1>Novo Contato</h1>
    </div>
    <div class="card-body">
      <%= render 'form', contato: @contato, departamentos: @departamentos %>
    </div>
  </div>
</div>

app/views/cadastro/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="row align-items-center">
        <div class="col-auto">
          <h1>Contato</h1>
        </div>
        <div class="col-auto row ml-auto">
          <%= button_to 'Editar', edit_cadastro_contato_path(@contato), method: :get, class: 'btn btn-primary col-auto mr-2', disabled: !cadastra? %>
          <%= button_to 'Voltar', cadastro_contatos_path, method: :get, class: 'btn btn-primary mr-3 col-auto' %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="form-row align-items-center">
        <div class="form-group col-auto">
          <%= label_tag :nome %>
          <%= text_field_tag :nome, @contato.nome, class: 'form-control', readonly: true %>
        </div>

        <div class="form-check col-auto">
          <div class="custom-control custom-checkbox">
            <%= check_box_tag :ativo, nil, @contato.ativo, class: 'custom-control-input', disabled: true %>
            <%= label_tag :ativo, 'Ativo', class: 'custom-control-label' %>
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-auto">
          <%= label_tag :telefone %>
          <%= text_field_tag :telefone, formata_telefone(@contato.telefone), class: 'form-control telefone-field', readonly: true %>
        </div>

        <div class="form-group col-auto">
          <%= label_tag :celular %>
          <%= text_field_tag :celular, formata_celular(@contato.celular), class: 'form-control celular-field', readonly: true %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-auto">
          <%= label_tag :departamento %>
          <%= text_field_tag :nome, @contato.departamento.nome, class: 'form-control', readonly: true %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-auto">
          <%= label_tag :cargo %>
          <%= text_field_tag :cargo, @contato.cargo, class: 'form-control', readonly: true %>
        </div>
      </div>
    </div>
  </div>
</div>