config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contatos', to: 'home#contatos', as: 'busca_contatos'
  post '/contatos', to: 'home#contatos'
  get '/departamentos', to: 'home#departamentos', as: 'busca_departamentos'
  post '/departamentos', to: 'home#departamentos'
  get 'locais', to: 'home#locais', as: 'busca_locais'
  post 'locais', to: 'home#locais'
  get '/usuarios/alterarsenha', to: 'usuarios#alterar_senha', as: 'alterar_senha'
  patch '/usuarios/alterarsenha', to: 'usuarios#atualizar_senha'
  devise_for :usuarios, controllers: { sessions: 'usuario/sessions' }
  namespace :cadastro do
    resources :contatos
    resources :departamentos
    resources :locais
  end
  resources :usuarios, except: :show
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :recoverable, :registerable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable, :rememberable
  validates :login, uniqueness: true, presence: true
  enum acesso: [:admin, :cadastro, :consulta]

  protected

  def email_required?
    false
  end
end

app/controllers/usuario/sessions_controller.rb
# frozen_string_literal: true

class Usuario::SessionsController < Devise::SessionsController
  skip_before_action :acesso_cadastro?
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    flash.clear
  end

  # DELETE /resource/sign_out
  def destroy
    super
    flash.clear
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :tem_acesso?
  before_action :set_usuario, only: [:edit, :update, :destroy]
  before_action :set_acessos, only: [:new, :edit, :create, :update]

  # GET /usuarios
  def index
    @q = Usuario.ransack(params[:q])
    @usuarios = @q.result.order(:login).page(params[:page])
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit; end

  # POST /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuarios_url, flash: { success: 'Usuario was successfully created.' } }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  def update
    limpa_senha! unless senha_alterada?
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuarios_url, flash: { success: 'Usuario was successfully updated.' } }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, flash: { success: 'Usuario was successfully destroyed.' } }
    end
  end

  def alterar_senha
    @usuario = current_usuario
  end

  def atualizar_senha
    @usuario = current_usuario

    if @usuario.update_with_password(set_password_params)
      bypass_sign_in @usuario
      redirect_to root_path, flash: { success: 'Senha alterada com sucesso.' }
    else
      render :alterar_senha
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def usuario_params
    params.require(:usuario).permit(:login, :email, :password, :password_confirmation, :acesso)
  end

  def set_acessos
    @acessos = Usuario.acessos
  end

  def tem_acesso?
    negar_acesso unless admin?
  end

  def senha_alterada?
    !params[:usuario][:password].blank? || !params[:usuario][:password_confirmation].blank?
  end

  def limpa_senha!
    params[:usuario].delete(:password)
    params[:usuario].delete(:password_confirmation)
  end

  def set_password_params
    params.require(:usuario).permit(:current_password, :password, :password_confirmation)
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
  def usuario_admin?(usuario)
    usuario.id.zero?
  end
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :login %>
      <%= form.text_field :login, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :senha %>
      <%= form.password_field :password, autocomplete: false, class: 'form-control' %>
    </div>

    <div class="form-group col-auto">
      <%= form.label :confirmacao_senha %>
      <%= form.password_field :password_confirmation, autocomplete: false, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-auto">
      <%= form.label :acesso %>
      <%= form.select :acesso, acessos.keys.collect { |k| [k,k] }, { prompt: 'Selecione' }, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
    <%= link_to 'Voltar', usuarios_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<%= model_erros_to_js_array usuario %>

app/views/usuarios/alterar_senha.html.erb
<div class="container main-container">
  <div class="pagination justify-content-center">
    <div class="col-md-6 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h1>Alterar Senha</h1>
        </div>
        <div class="card-body">
          <%= form_for @usuario, url: alterar_senha_path do |f| %>
            <div class="form-group">
              <%= f.label :current_password %>
              <%= f.password_field :current_password, autocomplete: false, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, autocomplete: false, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, autocomplete: false, class: 'form-control' %>
            </div>

            <div class="pagination justify-content-center">
              <div id="botoes">
                <%= f.submit 'Alterar', class: 'btn btn-primary' %>
                <%= link_to 'Cancelar', root_path, class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/usuarios/edit.html.erb
<div class="container main-container">
  <div class="card">
    <div class="card-header">
      <h1>Editar Usuário</h1>
    </div>
    <div class="card-body">
      <%= render 'form', usuario: @usuario, acessos: @acessos %>
    </div>
  </div>
</div>

app/views/usuarios/index.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-auto">
      <h1>Cadastro de Usuários</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-auto mr-auto">
      <%= search_form_for @q, class: 'form-inline mb-3' do |f| %>
        <div class="form-group">
          <%= f.label :login %>
          <%= f.search_field :login_cont, class: 'form-control ml-3' %>
        </div>

        <div class="form-group ml-3 mr-3">
          <%= f.label :email %>
          <%= f.search_field :email_cont, class: 'form-control ml-3' %>
        </div>

        <div id="submit">
          <%= f.submit 'Buscar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-auto mr-auto mb-3">
      <%= link_to 'Novo Usuário', new_usuario_path, class: 'btn btn-primary mt-1' %>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :login, 'Login', default_order: :asc) %></th>
        <th><%= sort_link(@q, :email, 'Email', default_order: :asc) %></th>
        <th><%= sort_link(@q, :acesso, 'Acesso', default_order: :asc) %></th>
        <th style="text-align: center">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.login %></td>
          <td><%= usuario.email %></td>
          <td><%= usuario.acesso %></td>
          <td style="text-align: center">
            <%= link_to fa_icon('pencil'), edit_usuario_path(usuario), class: 'btn btn-primary btn-sm' %>
            <% unless usuario_admin?(usuario) %>
              <%= link_to fa_icon('trash'), usuario, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pagination justify-content-center">
  <%= paginate @usuarios, theme: 'twitter-bootstrap-4' %>
</div>

app/views/usuarios/new.html.erb
<div class="container main-container">
  <div class="card">
    <div class="card-header">
      <h1>Novo Usuário</h1>
    </div>
    <div class="card-body">
      <%= render 'form', usuario: @usuario, acessos: @acessos %>
    </div>
  </div>
</div>