config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/contatos', to: 'home#contatos', as: 'busca_contatos'
  post '/contatos', to: 'home#contatos'
  get '/departamentos', to: 'home#departamentos', as: 'busca_departamentos'
  post '/departamentos', to: 'home#departamentos'
  get 'locais', to: 'home#locais', as: 'busca_locais'
  post 'locais', to: 'home#locais'
  get '/usuarios/alterarsenha', to: 'usuarios#alterar_senha', as: 'alterar_senha'
  patch '/usuarios/alterarsenha', to: 'usuarios#atualizar_senha'
  devise_for :usuarios, controllers: { sessions: 'usuario/sessions' }
  namespace :cadastro do
    resources :contatos
    resources :departamentos
    resources :locais
  end
  resources :usuarios, except: :show
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to application_name, root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Contatos', contatos_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Departamentos', departamentos_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Locais', locais_path, class: 'nav-link' %>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <% if cadastra? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cadastro
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Contatos', cadastro_contatos_path, class: 'dropdown-item' %>
              <%= link_to 'Departamentos', cadastro_departamentos_path, class: 'dropdown-item' %>
              <%= link_to 'Locais', cadastro_locais_path, class: 'dropdown-item' %>
              <% if admin? %>
                <%= link_to 'Usuários', usuarios_path, class: 'dropdown-item' %>
              <% end %>
            </div>
          </li>
        <% end %>

        <% unless usuario_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Login', new_usuario_session_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon 'user', text: current_usuario.login %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Alterar Senha', alterar_senha_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Sair', destroy_usuario_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListaTelefonica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

    <script type="text/javascript">
      <% flash.each do |k, v| %>
        $(document).ready(function() {
          $.notify("<%= v %>", "<%= tipo_notificacao[k.to_sym] %>")
          console.log("<%= k.to_sym %>")
          console.log("<%= tipo_notificacao[k.to_sym] %>")
        });
      <% end %>
    </script>
  </body>
</html>